"""Study design: can a run-in consistency score predict who drops out?

The workflow this package is meant to support:

1. Participants enrol. You observe them for a short **run-in** window.
2. From that window alone you compute a consistency score.
3. You follow them up, and relate the score to time-until-disengagement with a
   Cox model, censoring the people still active at the end.

The question this example answers is the one that has to be settled *before*
collecting data: given an effect of a plausible size, how long does the run-in
have to be, and how many participants do you need?

READ THIS BEFORE QUOTING ANY NUMBER BELOW. The cohort is generated by
:func:`~adherence.simulate.simulate_linked_cohort`, which *builds in* the
dependence between irregularity and dropout. Recovering it here is not evidence
that the effect is real -- it was assumed. What is being measured is the loss
between the true effect and the detectable one: the score is estimated from a
short, noisy history, and that attenuation is real, quantifiable, and the thing
that determines your sample size.

    python examples/cohort_power.py
"""

import numpy as np

import sys
from pathlib import Path

# Run straight from a clone, with or without `pip install -e .`.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from adherence import RoutineModel, timing_consistency
from adherence.events import SECONDS_PER_DAY
from adherence.simulate import simulate_linked_cohort
from adherence.survival import cox_ph

TRUE_LOG_HR = 0.35  # per SD of irregularity; HR ~1.4, a realistic size for this field
FOLLOW_UP_DAYS = 180
RUN_IN_WEEKS = (1, 2, 4, 8)


def score_run_in(log, run_in_days: float, model: RoutineModel) -> float:
    """Consistency from the run-in window only -- no peeking at follow-up."""
    cutoff = log.t_start + run_in_days * SECONDS_PER_DAY
    window = log.slice(t_to=cutoff)
    if len(window) < 3:
        return np.nan
    return timing_consistency(window, model, now=cutoff)


def _cox_for_run_in(cohort, days: float, model: RoutineModel):
    """Fit the Cox model using only what was observable during the run-in."""
    rows = []
    for log, truth in cohort:
        # People who quit during the run-in cannot be scored by it, and their
        # follow-up clock has to start where the run-in ends -- otherwise the
        # score would be credited with time it already got to observe.
        if truth["dropout_day"] is not None and truth["dropout_day"] < days:
            continue
        s = score_run_in(log, days, model)
        if np.isfinite(s):
            rows.append((s, truth["survived_days"] - days,
                         float(truth["dropout_day"] is not None)))
    if len(rows) < 20:
        return None, len(rows)
    s = np.array([r[0] for r in rows])
    if s.std() == 0:
        return None, len(rows)
    # Sign flipped so the covariate is irregularity, comparable with the truth.
    x = -(s - s.mean()) / s.std()
    fit = cox_ph(x[:, None], np.array([r[1] for r in rows]),
                 np.array([r[2] for r in rows]))
    return fit, len(rows)


def run(n: int = 300, n_cohorts: int = 8) -> None:
    """Averaged over several simulated cohorts: one cohort is far too noisy."""
    model = RoutineModel(bandwidth_min=45.0, half_life_days=28.0)
    print(f"n = {n} per cohort, {n_cohorts} cohorts, follow-up {FOLLOW_UP_DAYS} days")
    print(f"true effect, as simulated: log HR = {TRUE_LOG_HR:+.2f} per SD of irregularity")

    oracle_coefs, event_rates = [], []
    by_week = {w: [] for w in RUN_IN_WEEKS}
    usable = {w: [] for w in RUN_IN_WEEKS}

    for seed in range(n_cohorts):
        cohort = simulate_linked_cohort(
            n=n, days=FOLLOW_UP_DAYS, log_hazard_ratio=TRUE_LOG_HR, rng=seed
        )
        time = np.array([t["survived_days"] for _, t in cohort], dtype=float)
        event = np.array([t["dropout_day"] is not None for _, t in cohort], dtype=float)
        z = np.array([np.log(t["true_jitter_min"]) for _, t in cohort])
        z = (z - z.mean()) / z.std()
        oracle_coefs.append(cox_ph(z[:, None], time, event).coef[0])
        event_rates.append(event.mean())

        for w in RUN_IN_WEEKS:
            fit, n_used = _cox_for_run_in(cohort, w * 7, model)
            if fit is not None:
                by_week[w].append((fit.coef[0], fit.p[0]))
                usable[w].append(n_used)

    ceiling = float(np.mean(oracle_coefs))
    print(f"{np.mean(event_rates):.0%} disengaged, {1 - np.mean(event_rates):.0%} censored\n")
    print("Ceiling -- fitting the unobservable true jitter directly:")
    # Slightly below the simulated value because the generator draws dropout as a
    # per-day Bernoulli, and a discrete-time hazard ratio is mildly compressed
    # relative to the continuous-time one Cox estimates.
    print(f"  mean log HR {ceiling:+.3f}   (vs {TRUE_LOG_HR:+.2f} simulated; the small "
          "gap is discrete- vs continuous-time hazard)\n")

    print("Using the consistency score estimated from a run-in window of:")
    print(f"{'run-in':>8s} {'usable n':>9s} {'mean log HR':>12s} {'SD':>7s} "
          f"{'% of ceiling':>13s} {'% p<0.05':>9s}")
    for w in RUN_IN_WEEKS:
        if not by_week[w]:
            print(f"{w:6d}w   (too few scorable participants)")
            continue
        coefs = np.array([c for c, _ in by_week[w]])
        ps = np.array([p for _, p in by_week[w]])
        print(f"{w:6d}w  {np.mean(usable[w]):9.0f} {coefs.mean():+12.3f} {coefs.std():7.3f} "
              f"{coefs.mean() / ceiling:12.0%} {(ps < 0.05).mean():9.0%}")

    print(
        "\nTwo separate losses, and they pull in opposite directions.\n"
        "  * The score is noisy when estimated from a short window, which\n"
        "    attenuates its coefficient toward zero -- classical measurement-error\n"
        "    bias in a predictor.\n"
        "  * A longer run-in measures the score better, but spends follow-up time\n"
        "    and discards everyone who quit during it, so the usable sample and the\n"
        "    remaining events both shrink.\n"
        "Power is what balances them, and it is why this has to be simulated rather\n"
        "than reasoned about: neither effect is visible in a standard sample-size\n"
        "formula."
    )


def power_curve(n_grid=(50, 100, 200, 400), run_in_days: int = 28,
                n_sims: int = 30, alpha: float = 0.05) -> None:
    """Fraction of simulated studies that reach significance, by sample size."""
    model = RoutineModel(bandwidth_min=45.0, half_life_days=28.0)
    print(f"\n\nPower at alpha={alpha}, {run_in_days}-day run-in, "
          f"{n_sims} simulated studies per point:")
    print(f"{'n enrolled':>11s} {'power':>7s} {'median log HR':>15s}")
    for n in n_grid:
        hits, coefs = 0, []
        for s in range(n_sims):
            cohort = simulate_linked_cohort(
                n=n, days=FOLLOW_UP_DAYS, log_hazard_ratio=TRUE_LOG_HR, rng=1000 + s
            )
            rows = []
            for log, truth in cohort:
                if truth["dropout_day"] is not None and truth["dropout_day"] < run_in_days:
                    continue
                sc = score_run_in(log, run_in_days, model)
                if np.isfinite(sc):
                    rows.append((sc, truth["survived_days"] - run_in_days,
                                 float(truth["dropout_day"] is not None)))
            if len(rows) < 20:
                continue
            x = np.array([r[0] for r in rows])
            x = -(x - x.mean()) / x.std()
            fit = cox_ph(x[:, None], np.array([r[1] for r in rows]),
                         np.array([r[2] for r in rows]))
            hits += fit.p[0] < alpha
            coefs.append(fit.coef[0])
        print(f"{n:11d} {hits / n_sims:7.0%} {np.median(coefs):15.3f}")


if __name__ == "__main__":
    run()
    power_curve()
